import chalk from 'chalk';
import * as fs from 'fs';
import * as path from 'path';

// File-based cache for video category checks (persists across restarts)
const CACHE_FILE = path.join(process.cwd(), 'cache', 'youtube-categories.json');
const CACHE_TTL = 7 * 24 * 60 * 60 * 1000; // 7 days cache (categories rarely change)

// In-memory cache loaded from file
let categoryCache: Map<string, { isMusic: boolean; timestamp: number }> = new Map();
let cacheLoaded = false;

interface YouTubeVideoResponse {
    items?: Array<{
        id?: string;
        snippet?: {
            categoryId?: string;
            channelTitle?: string;
            description?: string;
        };
        topicDetails?: {
            topicCategories?: string[];
        };
    }>;
}

/**
 * Load cache from file
 */
function loadCache(): void {
    if (cacheLoaded) return;
    
    try {
        if (fs.existsSync(CACHE_FILE)) {
            const data = JSON.parse(fs.readFileSync(CACHE_FILE, 'utf-8'));
            categoryCache = new Map(Object.entries(data));
            console.log(`[${chalk.cyanBright('YOUTUBE')}] Loaded ${categoryCache.size} cached category entries`);
        }
    } catch (error) {
        console.error(`[${chalk.redBright('YOUTUBE')}] Error loading cache:`, error);
        categoryCache = new Map();
    }
    cacheLoaded = true;
}

/**
 * Save cache to file
 */
function saveCache(): void {
    try {
        const cacheDir = path.dirname(CACHE_FILE);
        if (!fs.existsSync(cacheDir)) {
            fs.mkdirSync(cacheDir, { recursive: true });
        }
        
        // Convert Map to object for JSON serialization
        const cacheObj: Record<string, { isMusic: boolean; timestamp: number }> = {};
        categoryCache.forEach((value, key) => {
            cacheObj[key] = value;
        });
        
        fs.writeFileSync(CACHE_FILE, JSON.stringify(cacheObj, null, 2));
    } catch (error) {
        console.error(`[${chalk.redBright('YOUTUBE')}] Error saving cache:`, error);
    }
}

/**
 * Check if a YouTube video is music content using YouTube Data API v3
 * 
 * Music content is identified by:
 * 1. categoryId === "10" (Music category)
 * 2. topicCategories containing music-related Wikipedia links
 * 3. Channel title ending with "- Topic" (auto-generated artist channels)
 * 
 * @param videoId - YouTube video ID (e.g., "dQw4w9WgXcQ")
 * @returns Promise<boolean> - true if the video is music content
 */
export async function isYouTubeMusicContent(videoId: string): Promise<boolean> {
    // Load cache from file if not loaded
    loadCache();
    
    // Check cache first
    const cached = categoryCache.get(videoId);
    if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
        return cached.isMusic;
    }

    const apiKey = process.env.YOUTUBE_API_KEY;
    if (!apiKey) {
        // No API key - fallback to assuming it's not music (will show as video)
        console.log(`[${chalk.yellowBright('YOUTUBE')}] No YOUTUBE_API_KEY set, skipping category check`);
        return false;
    }

    try {
        const url = `https://www.googleapis.com/youtube/v3/videos?part=snippet,topicDetails&id=${videoId}&key=${apiKey}`;
        const response = await fetch(url);
        
        if (!response.ok) {
            console.error(`[${chalk.redBright('YOUTUBE')}] API error: ${response.status} ${response.statusText}`);
            return false;
        }

        const data: YouTubeVideoResponse = await response.json();
        const video = data.items?.[0];

        if (!video) {
            return false;
        }

        // Check 1: Category ID = 10 (Music)
        const isMusicCategory = video.snippet?.categoryId === '10';

        // Check 2: Topic categories contain music-related topics
        const topics = video.topicDetails?.topicCategories || [];
        const hasMusicTopic = topics.some(url => 
            url.includes('wiki/Music') || 
            url.includes('wiki/Pop_music') ||
            url.includes('wiki/Rock_music') ||
            url.includes('wiki/Hip_hop_music') ||
            url.includes('wiki/Electronic_music') ||
            url.includes('wiki/Classical_music') ||
            url.includes('wiki/Jazz') ||
            url.includes('wiki/Country_music') ||
            url.includes('wiki/R%26B') ||
            url.includes('wiki/Soul_music')
        );

        // Check 3: Auto-generated artist channel (ends with "- Topic")
        const isTopicChannel = video.snippet?.channelTitle?.endsWith(' - Topic') || false;

        // Check 4: Description indicates music distribution
        const description = video.snippet?.description?.toLowerCase() || '';
        const isMusicDistribution = description.includes('provided to youtube by') ||
                                    description.includes('auto-generated by youtube');

        const isMusic = isMusicCategory || hasMusicTopic || isTopicChannel || isMusicDistribution;

        // Cache the result and save to file
        categoryCache.set(videoId, { isMusic, timestamp: Date.now() });
        saveCache();

        console.log(`[${chalk.cyanBright('YOUTUBE')}] Video ${videoId}: isMusic=${isMusic} (cat=${video.snippet?.categoryId}, topic=${hasMusicTopic}, topicCh=${isTopicChannel})`);

        return isMusic;
    } catch (error) {
        console.error(`[${chalk.redBright('YOUTUBE')}] Error checking category:`, error);
        return false;
    }
}

/**
 * Batch check multiple video IDs for music content
 * YouTube API allows up to 50 IDs per request (costs 1 unit total, not per video!)
 * 
 * @param videoIds - Array of YouTube video IDs
 * @returns Promise<Map<string, boolean>> - Map of videoId to isMusic
 */
export async function batchCheckMusicContent(videoIds: string[]): Promise<Map<string, boolean>> {
    // Load cache from file if not loaded
    loadCache();
    
    const results = new Map<string, boolean>();
    const uncachedIds: string[] = [];

    // Check cache first
    for (const id of videoIds) {
        const cached = categoryCache.get(id);
        if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
            results.set(id, cached.isMusic);
        } else {
            uncachedIds.push(id);
        }
    }

    if (uncachedIds.length === 0) {
        return results;
    }

    const apiKey = process.env.YOUTUBE_API_KEY;
    if (!apiKey) {
        // No API key - assume all are not music
        for (const id of uncachedIds) {
            results.set(id, false);
        }
        return results;
    }

    try {
        // YouTube API allows up to 50 IDs per request
        const batchSize = 50;
        for (let i = 0; i < uncachedIds.length; i += batchSize) {
            const batch = uncachedIds.slice(i, i + batchSize);
            const idsParam = batch.join(',');
            
            const url = `https://www.googleapis.com/youtube/v3/videos?part=snippet,topicDetails&id=${idsParam}&key=${apiKey}`;
            const response = await fetch(url);

            if (!response.ok) {
                console.error(`[${chalk.redBright('YOUTUBE')}] Batch API error: ${response.status}`);
                for (const id of batch) {
                    results.set(id, false);
                }
                continue;
            }

            const data: YouTubeVideoResponse = await response.json();
            
            // Create a map of video ID to response data
            const videoDataMap = new Map<string, typeof data.items[0]>();
            for (const item of data.items || []) {
                if (item.id) {
                    videoDataMap.set(item.id, item);
                }
            }
            
            // Process each video in the batch
            for (const videoId of batch) {
                const video = videoDataMap.get(videoId);
                
                if (!video) {
                    // Video not found in response - might be private/deleted
                    results.set(videoId, false);
                    categoryCache.set(videoId, { isMusic: false, timestamp: Date.now() });
                    continue;
                }

                const isMusicCategory = video.snippet?.categoryId === '10';
                const topics = video.topicDetails?.topicCategories || [];
                const hasMusicTopic = topics.some(url => 
                    url.includes('wiki/Music') || 
                    url.includes('wiki/Pop_music') ||
                    url.includes('wiki/Rock_music') ||
                    url.includes('wiki/Hip_hop_music') ||
                    url.includes('wiki/Electronic_music')
                );
                const isTopicChannel = video.snippet?.channelTitle?.endsWith(' - Topic') || false;
                const description = video.snippet?.description?.toLowerCase() || '';
                const isMusicDistribution = description.includes('provided to youtube by') ||
                                            description.includes('auto-generated by youtube');

                const isMusic = isMusicCategory || hasMusicTopic || isTopicChannel || isMusicDistribution;
                
                results.set(videoId, isMusic);
                categoryCache.set(videoId, { isMusic, timestamp: Date.now() });
            }
        }
        
        // Save cache after batch processing
        saveCache();
        console.log(`[${chalk.cyanBright('YOUTUBE')}] Batch checked ${uncachedIds.length} videos`);
        
    } catch (error) {
        console.error(`[${chalk.redBright('YOUTUBE')}] Batch check error:`, error);
        for (const id of uncachedIds) {
            if (!results.has(id)) {
                results.set(id, false);
            }
        }
    }

    return results;
}

/**
 * Clear the category cache (useful for testing or memory management)
 */
export function clearCategoryCache(): void {
    categoryCache.clear();
}

/**
 * Get cache statistics
 */
export function getCacheStats(): { size: number; hitRate: number } {
    return {
        size: categoryCache.size,
        hitRate: 0 // Would need to track hits/misses for accurate rate
    };
}
